<?php

function trusk_get_room_features() {
	// Define the features array
	$features = array(
		array(
			'id'    => 'balkon',
			'name'  => 'Балкон',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'bide',
			'name'  => 'Біде',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'dush',
			'name'  => 'Душ',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'dytyache_lizhechko',
			'name'  => 'Дитяче ліжечко',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'dyvan_ne_rozkladnyj',
			'name'  => 'Диван нерозкладний',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'dyvan_rozkladnyj',
			'name'  => 'Диван розкладний',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'dzhakuzi',
			'name'  => 'Джакузі',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'elektrochajnyk',
			'name'  => 'Електрочайник',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'fen',
			'name'  => 'Фен',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'halat',
			'name'  => 'Халат',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'holodylnyk',
			'name'  => 'Холодильник',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kabelne_telebachennya',
			'name'  => 'Кабельне телебачення',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kamin',
			'name'  => 'Камін',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kavachaj_v_nomeri',
			'name'  => 'Кава/чай в номері',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kavomashyna',
			'name'  => 'Кавомашина',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'komplekt_tualetnogo_pryladdya',
			'name'  => 'Комплект туалетного приладдя',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kondytsioner',
			'name'  => 'Кондиціонер',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'kuhnya',
			'name'  => 'Кухня',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'lizhko_dvospalne',
			'name'  => 'Ліжко двоспальне',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request,custom|Custom',
		),
		array(
			'id'    => 'lizhko_dvospalne_opys',
			'name'  => 'Опис двоспального ліжка',
			'type'  => 'text',
			'value' => '',
		),
		array(
			'id'    => 'lizhko_odnospalne',
			'name'  => 'Ліжко односпальне',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'mikrohvylova_pich',
			'name'  => 'Мікрохвильова піч',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'mini_bar',
			'name'  => 'Міні-бар',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'myake_krislo',
			'name'  => 'М’яке крісло',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'myakyj_kutok',
			'name'  => 'М’який куточок',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'nabir_posudu',
			'name'  => 'Набір посуду',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'nabir_rushnykiv',
			'name'  => 'Набір рушників',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'obidnij_stil',
			'name'  => 'Обідній стіл',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'pralna_mashyna',
			'name'  => 'Пральна машина',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'praska',
			'name'  => 'Праска',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'prylizhkovi_tumbochky',
			'name'  => 'Приліжкові тумбочки',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'robochyj_stil',
			'name'  => 'Робочий стіл',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'sanvuzel',
			'name'  => 'Санвузол',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'sauna',
			'name'  => 'Сауна',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'sejf',
			'name'  => 'Сейф',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'shafa_dlya_odyagu',
			'name'  => 'Шафа для одягу',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'shafa_kupe',
			'name'  => 'Шафа-купе',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'suputnykove_telebachennya',
			'name'  => 'Супутникове телебачення',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'tapochky',
			'name'  => 'Тапочки',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'telefon',
			'name'  => 'Телефон',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'televizor',
			'name'  => 'Телевізор',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'vanna',
			'name'  => 'Ванна',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
		array(
			'id'    => 'zona_vidpochynku',
			'name'  => 'Зона відпочинку',
			'type'  => 'radio',
			'value' => 'yes|Yes,no|No,on_request|Request',
		),
	);
	return $features;
}
